# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('c_image', models.ImageField(upload_to='')),
                ('party_affiliate', models.CharField(choices=[('Democratic', 'Democratic'), ('Republican', 'Republican'), ('Third Party', 'Third Party')], max_length=11)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Election_Info',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidates_choice', multiselectfield.db.fields.MultiSelectField(choices=[('Hillary Clinton', 'Hillary Clinton'), ('Sasuke Uchiha', 'Sasuke Uchiha'), ('Uzumaki Naruto', 'Uzumaki Naruto'), ('Michelle Obama', 'Michelle Obama')], max_length=50)),
                ('e_name', models.CharField(max_length=100)),
                ('e_description', models.TextField()),
                ('year', models.IntegerField(choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2016)),
                ('position', models.CharField(choices=[('Precinct committeewoman, committeeman', 'Precinct committeewoman, committeeman'), ('School Board Member/School Board President', 'School Board Member/School Board President'), ('Township/Village Trustee/Town Council', 'Township/Village Trustee/Town Council'), ('At-Large Councilwoman/man', 'At-Large Councilwoman/man'), ('City Ward Councilwoman/man', 'City Ward Councilwoman/man'), ('President of City Council', 'President of City Council'), ('City Law Director', 'City Law DIrector'), ('City Auditor', 'City Auditor'), ('City Treasurer', 'City Treasurer'), ('City Manager', 'City Manager'), ('Clerk of Court', 'Clerk of Court'), ('Common Pleas Court Judge', 'Common Pleas Court'), ('County Recorder', 'County Recorder'), ('County Coroner', 'County Coroner'), ('County Prosecuting Attorney', 'County Prosecuting Attorney'), ('County Treasurer', 'County Treasurer'), ('County Engineer', 'County Engineer'), ('County Auditor', 'County Auditor'), ('County Executives', 'County Execitives'), ('Board of County Commissioners', 'Board of County Comissioner'), ('Democrat/Republican State Central Committee', 'Democrat/Republican State Central Committee'), ('State Representative', 'State Representative'), ('State Senator', 'State Senator')], max_length=50)),
                ('precincts_range', multiselectfield.db.fields.MultiSelectField(choices=[(50001, 50001), (50101, 50101), (50201, 50201), (50301, 50301), (50401, 50401), (50501, 50501), (50601, 50601), (50701, 50701), (50801, 50801), (50901, 50901), (51001, 51001), (51101, 51101), (51201, 51201), (51301, 51301), (51401, 51401), (51501, 51501), (51601, 51601), (51701, 51701), (51801, 51801), (51901, 51901), (52001, 52001), (52101, 52101), (52201, 52201), (52301, 52301), (52401, 52401), (52501, 52501), (52601, 52601), (52701, 52701), (52801, 52801)], max_length=173)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='candidates',
            unique_together=set([('first_name', 'last_name', 'dob')]),
        ),
    ]
