# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20161203_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='c_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='election_info',
            name='candidates_choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sakura Haruna', 'Sakura Haruna'), ('Sasuke Uchiha', 'Sasuke Uchiha'), ('Uzumaki Naruto', 'Uzumaki Naruto'), ('Buttercup Oie', 'Buttercup Oie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='election_info',
            name='precincts_range',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('50001 - 50101', '50001 - 50101'), ('50102 - 50202', '50102 - 50202'), ('50203 - 50303', '50203 - 50303'), ('50304 - 50404', '50304 - 50404'), ('50405 - 50505', '50405 - 50505'), ('50506 - 50606', '50506 - 50606'), ('50607 - 50707', '50607 - 50707'), ('50708 - 50808', '50708 - 50808'), ('50809 - 50909', '50809 - 50909'), ('50910 - 51010', '50910 - 51010'), ('51011 - 51111', '51011 - 51111'), ('51112 - 51212', '51112 - 51212'), ('51213 - 51313', '51213 - 51313'), ('51314 - 51414', '51314 - 51414'), ('51415 - 51515', '51415 - 51515'), ('51516 - 51616', '51516 - 51616'), ('51617 - 51717', '51617 - 51717'), ('51718 - 51818', '51718 - 51818'), ('51819 - 51919', '51819 - 51919'), ('51920 - 52020', '51920 - 52020'), ('52021 - 52121', '52021 - 52121'), ('52122 - 52222', '52122 - 52222'), ('52223 - 52323', '52223 - 52323'), ('52324 - 52424', '52324 - 52424'), ('52425 - 52525', '52425 - 52525'), ('52526 - 52626', '52526 - 52626'), ('52627 - 52727', '52627 - 52727'), ('52728 - 52828', '52728 - 52828')], max_length=391),
        ),
    ]
